name: Nexus Blaine Watcher

- name: Twilio direct test (WhatsApp)
  env:
    TWILIO_SID:    ${{ secrets.TWILIO_SID }}
    TWILIO_TOKEN:  ${{ secrets.TWILIO_TOKEN }}
  run: |
    python - << 'PY'
    import os, base64, urllib.request, urllib.parse
    sid=os.getenv("TWILIO_SID"); tok=os.getenv("TWILIO_TOKEN")
    FROM="whatsapp:+14155238886"           # Twilio sandbox
    TO="whatsapp:+16049615235"             # your number with whatsapp: prefix
    AUTH=base64.b64encode(f"{sid}:{tok}".encode()).decode()
    data=urllib.parse.urlencode({"From":FROM,"To":TO,"Body":"Twilio ✅ test from GitHub Actions"}).encode()
    req=urllib.request.Request(f"https://api.twilio.com/2010-04-01/Accounts/{sid}/Messages.json",
                               data=data, method="POST",
                               headers={"Authorization":f"Basic {AUTH}","Content-Type":"application/x-www-form-urlencoded"})
    with urllib.request.urlopen(req,timeout=10) as r: print("[ok]",r.status)
    PY

on:
  schedule:
    - cron: "*/5 * * * *"        # optional (keeps 5-min backup schedule)
  repository_dispatch:
    types: [ping]                # <— listens for our external trigger
  workflow_dispatch: {}          # manual Run workflow button

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run watcher
        env:
          # Date include-only window for October 2025
          INCLUDE_START: "2026-02-12"
          INCLUDE_END: "2026-02-15"
          # Twilio WhatsApp (store sensitive values as repo secrets)
          TWILIO_SID: "${{ secrets.TWILIO_SID }}"
          TWILIO_TOKEN: "${{ secrets.TWILIO_TOKEN }}"
          WHATSAPP_FROM: "whatsapp:+14155238886"   # Twilio Sandbox; replace if you have a WA-enabled number
          WHATSAPP_TO:   "whatsapp:+16049615235"   # your phone number with country code
          # Optional: Telegram / Email envs can also be set here via secrets
        run: |
          python nexus_blaine_watcher.py
