name: Nexus Blaine Watcher (SMS, fast)

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  repository_dispatch:
    types: [ping]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    concurrency:
      group: nexus-watcher
      cancel-in-progress: true
    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # No pip install step (stdlib only) → runs finish in ~3–6s

      - name: Run watcher (SMS)
        env:
          # ---- Date window (February 2026) ----
          INCLUDE_START: "2026-02-01"
          INCLUDE_END:   "2026-02-28"

          # ---- Blaine ----
          LOCATION_ID: "5020"
          LIMIT: "50"

          # ---- Twilio SMS ----
          TWILIO_SID:    ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN:  ${{ secrets.TWILIO_TOKEN }}
          SMS_FROM:      "+12298002359"       # your Twilio SMS number
          SMS_TO:        "+1YOURNUMBER"       # or "+1A,+1B" comma-separated
        run: python nexus_blaine_watcher.py