name: Twilio WhatsApp Test

on:
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Send WhatsApp via Twilio API
        env:
          TWILIO_SID:    ${{ secrets.TWILIO_SID }}
          TWILIO_TOKEN:  ${{ secrets.TWILIO_TOKEN }}
          WHATSAPP_FROM: "whatsapp:+14155238886"  # sandbox sender (or your WA-enabled number)
          WHATSAPP_TO:   "whatsapp:+16049615235"  # your phone
        run: |
          set -euo pipefail
          basic_auth=$(printf "%s:%s" "$TWILIO_SID" "$TWILIO_TOKEN" | base64)
          curl -sS -X POST "https://api.twilio.com/2010-04-01/Accounts/$TWILIO_SID/Messages.json" \
            -H "Authorization: Basic $basic_auth" \
            -H "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "From=$WHATSAPP_FROM" \
            --data-urlencode "To=$WHATSAPP_TO" \
            --data-urlencode "Body=Twilio WhatsApp test from GitHub Actions" \
            -D /tmp/headers.txt \
            -o /tmp/body.json
          echo "Status headers:"; cat /tmp/headers.txt
          echo "Body:"; head -c 1000 /tmp/body.json; echo